name: Update Docker Hub Description

on:
  push:
    branches:
      - main
    paths:
      - "README.md"

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
          short-description: ${{ github.event.repository.description }}
